name = "broker-app"
account_id = "7a25071bd379490c242277ea870df57a"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "broker-app"

# D1 Database for user authentication and data
[[d1_databases]]
binding = "BROKER_DB"
database_name = "broker-app-db"
database_id = "6afc1f63-d680-4672-977b-2687c104c1cd"

# KV namespace for sessions (optional, can use D1 instead)
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"

# Worker-specific Hyperdrive binding (database access)
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "aae1a977e7a94a6db8088b4d6759296c"

# Development database connection
[[env.development.hyperdrive]]
binding = "HYPERDRIVE"
id = "aae1a977e7a94a6db8088b4d6759296c"
localConnectionString = "postgresql://postgres:uZys07ojDj22sZu@localhost:5432/postgres"

# Production database connection
[[env.production.hyperdrive]]
binding = "HYPERDRIVE"
id = "aae1a977e7a94a6db8088b4d6759296c"